# Generated by Django 2.2 on 2019-04-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=60, null=True, verbose_name='Razón Social')),
                ('telefono1', models.CharField(blank=True, max_length=13, null=True, verbose_name='Teléfono 1')),
                ('telefono2', models.CharField(blank=True, max_length=13, null=True, verbose_name='Teléfono 2')),
                ('vendedor', models.CharField(blank=True, max_length=30, null=True)),
                ('actividad', models.CharField(blank=True, max_length=30, null=True)),
                ('id_referencia', models.IntegerField(null=True, unique=True, verbose_name='Código Sistema de Gestión')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_tel', models.CharField(blank=True, choices=[('movil', 'Celular'), ('work', 'Trabajo'), ('home', 'Casa'), ('other', 'Otro')], max_length=5, null=True, verbose_name='Tipo Teléfono')),
                ('area_tel', models.CharField(blank=True, max_length=5, null=True, verbose_name='Area Teléfono')),
                ('numero_tel', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Nro. Teléfono')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('empresas', models.ManyToManyField(blank=True, related_name='contacto_empresas', to='contactos.Empresa')),
            ],
        ),
    ]
